server:
  port: 8182

spring:
  profiles:
    active: '@profile.active@'
  application:
    name: blog-gateway
  cloud:
    nacos:
      discovery:
        #服务发现地址
        server-addr: http://192.168.43.178:8848
      config:
        # 配置中心地址
        server-addr: http://192.168.43.178:8848
        # 修改文件扩展名
        file-extension: yaml
        # 缺省即可
        group: DEFAULT_GROUP
        # 缺省即可: 配置文件名前缀
        prefix: ${spring.application.name}
    bootstrap:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true # 启用自动根据服务ID生成路由
          lower-case-service-id: true # 设置路由的路径为小写的服务ID
      routes:
        - id: blog-admin
          uri: lb://blog-admin
          predicates:
            #匹配路由
            - Path=/api/admin/**
        - id: blog-auth
          uri: lb://blog-auth
          predicates:
            #匹配路由
            - Path=/api/auth/**
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.43.178
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0